# Nom du workflow, visible dans l'interface GitHub
name: Python Flask CI

# Déclencheurs: s'exécute à chaque push ou pull request sur la branche main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Liste des missions à accomplir
jobs:
  # Notre première et unique mission
  build-and-test:
    # Le type de machine virtuelle à utiliser
    runs-on: ubuntu-latest

    # La séquence d'étapes pour cette mission
    steps:
    # 1. Récupère le code de votre dépôt sur la VM
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Installe Python 3.10 sur la VM
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 3. Installe nos dépendances via pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Exécute notre contrôle qualité
    - name: Run tests with pytest
      run: pytest
